version: "3.9"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    build: ./backend
    command: npm run start
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
volumes:
  mongo_data:
